# Generated by Django 3.2.4 on 2021-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0003_step_course_sub_step_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step_course',
            name='step_course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_step_course',
            name='sub_step_course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
