# Generated by Django 3.2.4 on 2021-06-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0004_auto_20210611_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Browse_Course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Browse_Course.step_course')),
            ],
        ),
    ]
