# Generated by Django 3.2.4 on 2021-06-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0006_sub_step_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_step_course',
            name='slug',
        ),
    ]
