# Generated by Django 3.2.4 on 2021-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0007_remove_sub_step_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_step_course',
            name='in_put',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sub_step_course',
            name='output',
            field=models.CharField(blank=True, default='0', max_length=1000),
        ),
    ]
