# Generated by Django 3.2.4 on 2021-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0008_auto_20210612_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_step_course',
            name='hint',
            field=models.TextField(default='Tidak ada petunjuk'),
        ),
    ]
