# Generated by Django 3.2.4 on 2021-06-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse_Course', '0009_sub_step_course_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_step_course',
            name='output',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
