# Generated by Django 3.2.4 on 2021-06-13 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Browse_Course', '0010_alter_sub_step_course_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
